### PR TITLE
[FIX] Filter subjects and sessions when querying modalities (issue #65)

### PR DESCRIPTION
**Pull request by gllmflndn**
It might be time to remove the remaining `switch`/`case` as there are no special cases any more.

### CODE REVIEW

**Comment by Remi-Gau** [comment]
And here a sentence you are going to hear me say often: "Can I add a test for that?" :wink:

Hoping that bit by bit we can increase our coverage.

**Comment by gllmflndn** [comment]
> And here a sentence you are going to hear me say often: "Can I add a test for that?" 😉

I thought you volunteered for that? :laughing: Otherwise I nominate @ChristophePhillips

**Comment by Remi-Gau** [comment]
> > And here a sentence you are going to hear me say often: "Can I add a test for that?" wink
> 
> I thought you volunteered for that? laughing Otherwise I nominate @ChristophePhillips

I wlll gladly do it but if @ChristophePhillips wants to have fun at it: be my guest.

**Review by Remi-Gau — APPROVED** [review]

**Comment by Remi-Gau** [comment]
> It might be time to remove the remaining `switch`/`case` as there are no special cases any more.

This looks good to me and yes that external switch seems a bit of an overkill though I think we need to have the error handling at the end.

**Comment by gllmflndn** [comment]
Thanks, I will leave the switch for now as a reminder of the former distinction between different queries (this might require further thoughts).
Also, the tests with `isequal` enforce a particular order, e.g. `{'anat','fmap','func'}`: we should probably relax this at some point.

**Pull request merged**
