### PR TITLE
[DOC] add orcid numbers to CITATION.CFF

### PR DESCRIPTION
**Pull request by Remi-Gau**
Adding ORCID numbers so they can show up on [our zenodo page](https://zenodo.org/record/5910585) on the next release

---
@gllmflndn @CPernet @ChristophePhillips @cMadan @robertoostenveld @mnoergaard @HenkMutsaerts 

Can you cross check that I got yours right?

---
@nbeliy @tanguyduval @apjanke @mslw 

I could not find yours, so let me know what it is or add it yourself (if you have one).

### CODE REVIEW

**Comment by tanguyduval** [comment]
Hi Remi, thanks. Mine is 0000-0002-1228-5192
(don't know how to add it myself sorry)
Best
Tanguy

**Comment by Remi-Gau** [comment]
> 0000-0002-1228-5192

@tanguyduval just added yours

**Comment by mslw** [comment]
Mine is: 0000-0002-4028-2087
Thanks a lot!

**Comment by Remi-Gau** [comment]
> 0000-0002-4028-2087

Done. :-)

**Pull request merged**
