### PR TITLE
[INFRA] run tests with github action

### PR DESCRIPTION
**Pull request by Remi-Gau**
- drop travis for gtihub actions

### CODE REVIEW

**Comment by Remi-Gau** [comment]
fix #68

**Comment by Remi-Gau** [comment]
Hum... Unclear as to why this action fails here but seemed to work fine on a PR on my own repo...

https://github.com/Remi-Gau/bids-matlab/pull/5

**Comment by gllmflndn** [comment]
Thanks for doing this @Remi-Gau. I temporarily forced the tests to use [ubuntu-20.04](https://github.blog/changelog/2020-10-29-github-actions-ubuntu-latest-workflows-will-use-ubuntu-20-04/) and they ran through. We can revert to `ubuntu-latest` when the switch is over.
It's probably just me but I would configure miss_hit to be informative (i.e. report full list of detected issues) but not fail as a test while the library is under heavy development (i.e. implements a should rather than a must).

**Comment by Remi-Gau** [comment]
> Thanks for doing this @Remi-Gau. I temporarily forced the tests to use [ubuntu-20.04](https://github.blog/changelog/2020-10-29-github-actions-ubuntu-latest-workflows-will-use-ubuntu-20-04/) and they ran through. We can revert to `ubuntu-latest` when the switch is over.

Cool thanks!!

> It's probably just me but I would configure miss_hit to be informative (i.e. report full list of detected issues) but not fail as a test while the library is under heavy development (i.e. implements a should rather than a must).

yeah it's just you!!! :wink: (that's my way of saying "happy new year!!!"! Have you missed me?)

I was thinking of a "smart" way of doing this (because I don't think that miss_hit has "warning only" mode at the moment): to align with the idea of developing stuff on a `dev` branch and keep the `master` branch, we could from now on work on the `dev` and configure the github action to run miss_hit only on `master` or PRs to master (I hope that github action allows to only run stuff on PR on a certain base branch).

Would that make sense?

**Comment by Remi-Gau** [comment]
https://stackoverflow.com/questions/63817052/github-actions-run-step-only-for-certain-pull-request-base-branches

Need to double check but something like this could do the trick:

```yaml
on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]
```

@gllmflndn  Would you be OK with that?

**Comment by Remi-Gau** [comment]
Unless I hear otherwise I will merge this in 2 days: this is mostly infrastructure related but it should make our lives easier moving forward.

**Review by sappelhoff — APPROVED** [review]

**Pull request merged**
