### PR TITLE
add code of conduct from bids-specs

### PR DESCRIPTION
**Pull request by Remi-Gau**
This is not meant to be a final version in any way but having something is better than nothing. We can try to improve and go beyond the COC of bids-specs with time.

### CODE REVIEW

**Comment by gllmflndn** [comment]
Concerning a Code of Conduct, I leave BIDS maintainers @Remi-Gau @robertoostenveld @sappelhoff decide which one is most appropriate for projects hosted on @bids-standard.

**Comment by robertoostenveld** [comment]
I believe there is a general one that applies to all repositories, unless explicitly overruled by a specific one. Unless there are good reasons otherwise, I suggest to stick to that one. 

See https://github.com/bids-standard/.github/blob/master/CODE_OF_CONDUCT.md. I must admit that I don't know how that actually works, i.e. how the one from `.github` is made to apply here.

**Comment by sappelhoff** [comment]
> See https://github.com/bids-standard/.github/blob/master/CODE_OF_CONDUCT.md. I must admit that I don't know how that actually works, i.e. how the one from .github is made to apply here.

when opening a new issue or PR, you will see a link to the bids-standard "default" COC on the lower right, see this screenshot:

grafik

---

It's not very visible unfortunately ... which is why I would be okay with adding it explicitly in this repo (as is also done at the BIDS-specification repo). See https://github.com/bids-standard/bids-specification/issues/364 for more information.

**Comment by apjanke** [comment]
> I believe there is a general one that applies to all repositories, unless explicitly overruled by a specific one.
> [...]
> See https://github.com/bids-standard/.github/blob/master/CODE_OF_CONDUCT.md. I must admit that I don't know how that actually works, i.e. how the one from .github is made to apply here.

I do not think that is the case. This thing you have linked to is a repo named ".github" - that's not a standard GitHub feature as far as I know, and I do not think it has any effect. The ".github" functionality is a per-repo thing, where you create a directory named `.github` inside each repo. I do not think creating a repo named `.github` has any effect, and I don't think there's any "inheritance" from it to the individual organizations inside your repo.

For example, when I view the `bids-matlab` repo, or create a new PR against `bids-matlab`, I do not see any banners or links for a code of conduct there.

This is what I see when looking at the bids-matlab repo:

image

And this is what I see when I create a new PR for the bids-matlab repo:

image

I don't see any CoC references anywhere in them.

I don't see the "Helpful Resources" section that @sappelhoff saw in their PR. (Maybe you could include the URL bar to make it clearer what you're making a PR against there?)

I think you need to add the CoC to each individual repo to have it take effect.

**Comment by Remi-Gau** [comment]
The link is there: below the comment box at the bottom.

```
Remember, contributions to this repository should follow its code of conduct. 
```

:arrow_down:

**Comment by apjanke** [comment]
Ohhh! My eyes slid *right* over that, even after several re-scans of the page; that's the section for "fine print that I've trained myself to completely ignore".

I kind of feel like a doofus now, but also think this maybe means it should be featured somewhere more prominent, if it could be.

**Comment by Remi-Gau** [comment]
The problem is not with you definitely. 

So that speaks in favor of having a COC in the repo I think. :-)

**Comment by Remi-Gau** [comment]
No veto on this until now so I am merging.

At least this gives a basis to improve on.

**Pull request merged**
