### PR TITLE
Tolerant option for bids.layout

### PR DESCRIPTION
**Pull request by tanguyduval**

### CODE REVIEW

**Comment by tanguyduval** [comment]
This issue solves #11 
Tolerance on:
- dataset_description and .tsv files
- parse image modalities that are not in BIDS yet (but in extension proposal for instance)

Other tolerant conditions that could be added:
- inconsistent data between subjects (currently it crashes if more images in one subject than another)

**Comment by Remi-Gau** [comment]
Nice.
Wouldn't it sense to have the inconsistency between subjects be the lowest level of tolerance: unless I am mistaken this does not make an invalid bids data set, where as the other 2 levels would.
Or am I missing something?

**Comment by tanguyduval** [comment]
@Remi-Gau agreed, I just tried an inconsistent dataset with bids validator and it gives no error. Only a warning in case of inconsistent data between subjects:
````
Warning 2: [Code 38] INCONSISTENT_SUBJECTS
Not all subjects contain the same files. Each subject should contain the same number of files with the same naming unless some files are known to be missing.
````

I'll change that.
Best

**Comment by tanguyduval** [comment]
@Remi-Gau this version accepts inconsistent data between subjects, even for files not officially in BIDS yet
tested on octave 5 and matlab.
Best

**Comment by Remi-Gau** [comment]
Thank. Will check things out during the weekend

**Comment by Remi-Gau** [comment]
- [ ] add tests to check warning VS error handling of the tolerant option of layout

**Comment by Remi-Gau** [comment]
If that's with everyone I will start mergin those old pull-requests that have not been "vetoed".
- bring the PR up to date with master
- clean up and refactor if needed
- create tests if needed or where easily possible
- wait for 24 hours after CI gives the green light (in case anyone has any final thoughts before merging)
- merge

**Comment by Remi-Gau** [comment]
On this one we would need some test to assert that a warning or an exception is thrown. 

Not sure that our current framework allows this.

**Review by Remi-Gau — APPROVED** [review]
Good with me

**Pull request merged**
